import type { Metadata } from "next";
import { Inter, IBM_Plex_Serif } from "next/font/google";
import "./globals.scss";
import Footer from "./components/footer";
import Header from "./components/navigation";
import { Blobs } from "./components/blobsLayout";

const inter = Inter({ subsets: ["latin"], variable: "--main-font" });
const IBM = IBM_Plex_Serif({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600", "700"],
  variable: "--accent-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}, ${IBM.variable}`}>
        <Blobs />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
