import type { Metadata } from "next";
import { Inter, IBM_Plex_Serif } from "next/font/google";
import "./globals.scss";
import Footer from "./components/footer";
import Navigation from "./components/navigation";
import Image from "next/image";
import Logo from "../../public/vet-logo.svg";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"], variable: "--main-font" });
const IBM = IBM_Plex_Serif({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "600", "700"],
  variable: "--accent-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(`${inter.variable}, ${IBM.variable}`)}>
        <header className="flex justify-center items-center w-28 py-4 bg-slate-100">
          <Image src={Logo} alt="Vercel Logo" priority width={80} />
        </header>
        <div className="flex gap-4">
          <div className="sticky top-0 h-full basis-28 shrink-0">
            <Navigation />
          </div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
